# Generated by Django 5.2.6 on 2025-09-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='title',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
